### PR TITLE
Make the script compatible with Debian sid (8.0)

### PR DESCRIPTION
**Pull request by xerothermic**
Needs to make a few small modifications to make it work with my Debian system.

Patrick

### CODE REVIEW

**Comment by xerothermic** [comment]
Ignore case that this:

# example

# title        Windows ...

#

**Comment by error10** [comment]
I can't accept commit 32bb480 as it breaks parsing on anything that _isn't_ Debian, for instance CentOS 6. On this system, for example, `root`, `kernel` and `initrd` are preceded by a tab.

Are you really using grub1 on sid? I thought Debian switched to grub2 with jessie. I've not yet tried sid, but will do so sometime this week.

**Comment by xerothermic** [comment]
I was wondering why do you use .+? instead of \n, now it makes sense. I changed the newline matching and verified it's detecting on CentOS based OS as well now.

Yes, I purposely still stay with grub1 as I have some RTOS and it's easier to deal with grub1 bootloader.

**Comment by error10** [comment]
Parts regarding optional initrd rejected, as all supported distro configurations use initrd

**Pull request closed without merging**
